# Generated by Django 5.0.1 on 2024-01-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porteiro',
            options={'verbose_name': 'Porteiro', 'verbose_name_plural': 'Porteiros'},
        ),
    ]
